services:
  postgres:
    container_name: postgres-spring-mvc-1
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: springmvc1
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-mvc
    restart: unless-stopped

#  cas-server:
#    image: apereo/cas:6.4.0
#    container_name: cas-server
#    ports:
#      - "8443:8443"
#    environment:
#      - CAS_AUTHN_ACCEPT_USERS=user::password
#      - CAS_AUTHN_ACCEPT_ENABLED=true
#      - server.ssl.key-store=/etc/cas/thekeystore.jks
#      - server.ssl.key-store-password=changeit
#      - server.ssl.key-alias=tomcat
#      - server.ssl.key-store-type=JKS
#      - server.port=8443
#    volumes:
#      - ./config/thekeystore.p12:/etc/cas/thekeystore.jks:ro
#    networks:
#      - spring-mvc
#    restart: unless-stopped


  mvc1:
    container_name: mvc1
    image: mvc1/mvc1:1.0.0
    ports:
      - 8083:8083
    networks:
      - spring-mvc
    depends_on:
      - postgres
networks:
  spring-mvc:
    driver: bridge

volumes:
  postgres:
    driver: local
#  cas-server:
#    driver: local
