services:
  postgres:
    container_name: postgres-spring-mvc-1
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: springmvc1
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-mvc
    restart: unless-stopped


  mvc1:
    container_name: mvc1
    image: mvc1/mvc1:1.0.0
    ports:
      - 8083:8083
    networks:
      - spring-mvc
    depends_on:
      - postgres
networks:
  spring-mvc:
    driver: bridge

volumes:
  postgres:
    driver: local
#  cas-server:
#    driver: local
