services:
  postgres:
    container_name: postgres-spring-mvc-1
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: springmvc1
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-mvc
    restart: unless-stopped

networks:
  spring-mvc:
    driver: bridge

volumes:
  postgres:
    driver: local