name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy Spring MVC Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 8

      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUB.USERNAME }}
          password: ${{ secrets.HUB.TOKEN }}


      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.HUB.USERNAME }}/mvc:latest
